const SONGS = [
  { id: 1, title: "Wildfeuer", key: "E-Moll", tempo: 138, duration: "4:12", mood: ["energiegeladen", "kraftvoll", "ausgelassen"], situation: ["konzert", "festival", "outdoor"], energy: 10, description: "Harter Opener – bringt die Menge sofort in Fahrt", lyrics: `STROPHE 1:\nFeuer bricht aus altem Stein\nGlut, die niemals wird allein\nWir sind wild und wir sind frei\nFogelwuid – da sind wir dabei\n\nSTROPHE 2:\nSturm zieht über Berg und Tal\nWir steh'n hier zum letzten Mal\nNein, zum ersten – spür die Kraft\nDie uns durch die Nacht erschafft\n\nREFRAIN:\nWildfeuer, Wildfeuer\nBrennt in uns'rer Brust\nWildfeuer, Wildfeuer\nVoller Lebenslust\nHey – Hey – Hey!\n\nBRIDGE:\n(Gitarren-Solo)\nDie Nacht gehört uns, die Nacht gehört uns!\n\nREFRAIN (2x)\n\nOUTRO:\nFeuer ... Feuer ... Feuer!` },
  { id: 2, title: "Hoamatland", key: "G-Dur", tempo: 96, duration: "3:58", mood: ["feierlich", "nachdenklich", "romantisch"], situation: ["konzert", "akustik", "zugabe"], energy: 5, description: "Herzstück – Heimatlied das bewegt", lyrics: `STROPHE 1:\nWenn i woascht, wo i herkimm\nDann waaß i, wer i bin\nDie Berge steh'n wie immer do\nI kimm immer wieder hin\n\nREFRAIN:\nHoamatland, Hoamatland\nDu bist alles was ich hab\nHoamatland, Hoamatland\nBis ich einmal geh` },
  { id: 3, title: "Sturmwind", key: "A-Moll", tempo: 152, duration: "3:34", mood: ["energiegeladen", "kraftvoll"], situation: ["konzert", "festival", "outdoor"], energy: 10, description: "Moshpit-Garantie", lyrics: `STROPHE 1:\nSchwarze Wolken zieh'n heran\nDer Donner rollt am Horizont\n\nREFRAIN:\nSturmwind, Sturmwind\nReiß uns mit in die Nacht\nSturmwind, Sturmwind\nHat uns stark gemacht\nSturmwind – STURMWIND!` },
  { id: 4, title: "Alpenglüh'n", key: "D-Dur", tempo: 112, duration: "4:28", mood: ["feierlich", "romantisch", "nachdenklich"], situation: ["konzert", "hochzeit", "akustik"], energy: 6, description: "Ballade mit Alpencharakter", lyrics: `STROPHE 1:\nWenn die Sonne hinter'm Berg verschwindet\nUnd das Abendrot den Himmel zündet\n\nREFRAIN:\nAlpenglüh'n, Alpenglüh'n\nBrennt in meinem Herz\nAlpenglüh'n, Alpenglüh'n\nTreibst mir fast die Tränen her` },
  { id: 5, title: "Bier & Brüder", key: "E-Dur", tempo: 130, duration: "3:22", mood: ["ausgelassen", "feierlich", "energiegeladen"], situation: ["party", "festival", "bar", "konzert"], energy: 9, description: "Mitgrölsong", lyrics: `REFRAIN:\nBier & Brüder – das ist alles\nBier & Brüder – was man braucht\nBier & Brüder – heut' und immer\nBier & Brüder – PROST!` },
  { id: 6, title: "Leise Wasser", key: "C-Dur", tempo: 72, duration: "5:02", mood: ["entspannt", "romantisch", "melancholisch"], situation: ["akustik", "hochzeit", "bar"], energy: 2, description: "Ruhige Ballade", lyrics: `STROPHE 1:\nLeise Wasser rauschen sacht\nDurch die stille Sommernacht\n\nREFRAIN:\nLeise Wasser, leise Wasser\nTragt mein Herz zu ihr` },
  { id: 7, title: "Auf geht's", key: "A-Dur", tempo: 145, duration: "3:10", mood: ["ausgelassen", "energiegeladen"], situation: ["konzert", "party", "festival", "outdoor"], energy: 9, description: "Absoluter Partykracher", lyrics: `REFRAIN:\nAuf geht's – auf geht's\nLos geht die wilde Nacht\nAuf geht's – auf geht's\nBis der Morgen lacht\nAuf geht's!` },
  { id: 8, title: "Bergkristall", key: "Fis-Moll", tempo: 88, duration: "4:44", mood: ["nachdenklich", "melancholisch", "romantisch"], situation: ["akustik", "konzert", "hochzeit"], energy: 4, description: "Tiefgründiges Lied über Vergänglichkeit", lyrics: `STROPHE 1:\nKlarer als das Bergewasser\nReiner als der Morgentau\n\nREFRAIN:\nBergkristall, Bergkristall\nBreche das Licht in tausend Farben` },
  { id: 9, title: "Nacht ohne Ende", key: "B-Moll", tempo: 118, duration: "4:05", mood: ["nachdenklich", "melancholisch", "kraftvoll"], situation: ["konzert", "bar", "akustik"], energy: 6, description: "Rock-Ballade mit emotionalem Aufbau", lyrics: `REFRAIN:\nNacht ohne Ende\nIch finde keinen Weg\nNacht ohne Ende\nWo führt mich dieser Steg?\nNacht ohne Ende – doch ich geh' weiter` },
  { id: 10, title: "Freie Seele", key: "D-Dur", tempo: 126, duration: "3:48", mood: ["feierlich", "ausgelassen", "energiegeladen"], situation: ["konzert", "festival", "outdoor", "party"], energy: 8, description: "Freiheitshymne", lyrics: `REFRAIN:\nFreie Seele, freie Seele\nFliege in den Morgen\nFreie Seele, freie Seele\nKeine Angst, kein Sorgen\nFreie Seele – ich bin frei!` },
  { id: 11, title: "Herzschlag", key: "C-Moll", tempo: 104, duration: "4:20", mood: ["kraftvoll", "energiegeladen", "feierlich"], situation: ["konzert", "festival"], energy: 8, description: "Starkes Rockstück", lyrics: `REFRAIN:\nHerzschlag – Herzschlag\nSchlägt für dich und mich\nHerzschlag – Herzschlag\nHält uns aufrecht, siehst du's nicht?\nHERZSCHLAG!` },
  { id: 12, title: "Sommernacht", key: "G-Dur", tempo: 88, duration: "4:38", mood: ["romantisch", "entspannt", "feierlich"], situation: ["hochzeit", "bar", "outdoor", "akustik"], energy: 4, description: "Perfekt für laue Sommernächte", lyrics: `REFRAIN:\nSommernacht, Sommernacht\nHält die Zeit für uns an\nSommernacht, Sommernacht\nWas du mit mir hast getan\nDu Sommernacht` },
  { id: 13, title: "Rausch der Freiheit", key: "E-Dur", tempo: 148, duration: "3:28", mood: ["energiegeladen", "kraftvoll", "ausgelassen"], situation: ["konzert", "festival", "outdoor"], energy: 10, description: "Maximale Energie", lyrics: `REFRAIN:\nRausch der Freiheit – triff mich jetzt\nRausch der Freiheit – alles setzt\nRausch der Freiheit – wir explodieren\nRAUSCH DER FREIHEIT!` },
  { id: 14, title: "Alter Freund", key: "F-Dur", tempo: 82, duration: "4:55", mood: ["nachdenklich", "melancholisch", "romantisch"], situation: ["akustik", "bar", "konzert", "zugabe"], energy: 3, description: "Nachdenklich – für Momente der Verbundenheit", lyrics: `REFRAIN:\nAlter Freund, alter Freund\nDu bist immer noch dabei\nAlter Freund, alter Freund\nMit dir bin ich niemals allein` },
  { id: 15, title: "Donnerhall", key: "D-Moll", tempo: 156, duration: "3:18", mood: ["energiegeladen", "kraftvoll"], situation: ["konzert", "festival"], energy: 10, description: "Brutalste Nummer", lyrics: `REFRAIN:\nDonnerhall – Donnerhall!\nReißt die Mauern nieder\nDonnerhall – Donnerhall!\nWir steh'n immer wieder\nDONNERHALL!` },
  { id: 16, title: "Morgenrot", key: "H-Dur", tempo: 100, duration: "4:15", mood: ["feierlich", "nachdenklich", "romantisch"], situation: ["konzert", "outdoor", "zugabe"], energy: 5, description: "Hoffnungsvoller Abschluss", lyrics: `REFRAIN:\nMorgenrot, Morgenrot\nMaler du des neuen Tags\nMorgenrot, Morgenrot\nGibst mir alles was ich mag` },
  { id: 17, title: "Tanznacht", key: "A-Dur", tempo: 132, duration: "3:42", mood: ["ausgelassen", "feierlich", "energiegeladen"], situation: ["party", "hochzeit", "bar", "festival"], energy: 8, description: "Absoluter Tanztreiber", lyrics: `REFRAIN:\nTanznacht, Tanznacht\nHört das Herz nicht auf zu schlagen\nTanznacht, Tanznacht\nKomm wir tanzen bis zum Morgen\nTanznacht!` },
  { id: 18, title: "Ewige Berge", key: "E-Moll", tempo: 78, duration: "5:20", mood: ["nachdenklich", "feierlich", "melancholisch"], situation: ["konzert", "akustik", "zugabe"], energy: 4, description: "Episches Stück – Hymne an die Natur", lyrics: `REFRAIN:\nEwige Berge, ewige Berge\nIhr habt mich aufgezogen\nEwige Berge, ewige Berge\nIhr habt mein Herz gesogen` },
  { id: 19, title: "Zündfunke", key: "G-Moll", tempo: 142, duration: "3:30", mood: ["energiegeladen", "kraftvoll", "ausgelassen"], situation: ["konzert", "festival", "outdoor"], energy: 9, description: "Zündende Energie", lyrics: `REFRAIN:\nZündfunke – springt über\nZündfunke – zündet durch\nZündfunke – wir brennen\nZÜNDFUNKE!` },
  { id: 20, title: "Bleib bei mir", key: "C-Dur", tempo: 76, duration: "4:50", mood: ["romantisch", "melancholisch", "entspannt"], situation: ["hochzeit", "bar", "akustik", "zugabe"], energy: 2, description: "Liebeslied", lyrics: `REFRAIN:\nBleib bei mir, bleib bei mir\nIch brauche keine and're Welt\nBleib bei mir, bleib bei mir\nDu bist alles was mich hält` },
  { id: 21, title: "Rock'n'Roll Herz", key: "B-Dur", tempo: 160, duration: "3:05", mood: ["energiegeladen", "ausgelassen"], situation: ["konzert", "festival", "party", "bar"], energy: 10, description: "Klassischer Rocker", lyrics: `REFRAIN:\nRock'n'Roll Herz – schlägt immer weiter\nRock'n'Roll Herz – macht alles leichter\nRock'n'Roll Herz – du bist mein Leben` },
  { id: 22, title: "Heimweg", key: "F-Moll", tempo: 86, duration: "4:32", mood: ["melancholisch", "nachdenklich", "entspannt"], situation: ["bar", "akustik", "konzert"], energy: 3, description: "Nachdenklicher Song", lyrics: `REFRAIN:\nHeim weg, Heimweg\nFührt mich durch die stille Stadt\nHeimweg, Heimweg\nBis ich wieder Schlaf und Rast` },
  { id: 23, title: "Sturzflut", key: "C-Moll", tempo: 150, duration: "3:40", mood: ["energiegeladen", "kraftvoll"], situation: ["konzert", "festival", "outdoor"], energy: 10, description: "Intensivstes Stück", lyrics: `REFRAIN:\nSTURZFLUT – reißt alles mit\nSTURZFLUT – nichts dagegen\nSTURZFLUT – Wir sind bereit\nSTURZFLUT!` },
  { id: 24, title: "Goldener Herbst", key: "G-Dur", tempo: 94, duration: "4:18", mood: ["romantisch", "nachdenklich", "feierlich"], situation: ["outdoor", "konzert", "hochzeit", "akustik"], energy: 5, description: "Poetisch", lyrics: `REFRAIN:\nGoldener Herbst, goldener Herbst\nDu schönste Zeit im Jahr\nGoldener Herbst, goldener Herbst\nMachst alles wunderbar` },
  { id: 25, title: "Adrenalin", key: "F-Dur", tempo: 158, duration: "3:12", mood: ["energiegeladen", "ausgelassen"], situation: ["konzert", "festival", "party"], energy: 10, description: "Reiner Adrenalinschub", lyrics: `REFRAIN:\nAdrenalin – pumpt durch die Adern\nAdrenalin – macht alles größer\nAdrenalin – wir sind unsterblich\nADRENALIN!` },
  { id: 26, title: "Stille Nacht, Laute Welt", key: "A-Moll", tempo: 68, duration: "5:35", mood: ["nachdenklich", "melancholisch"], situation: ["akustik", "bar", "konzert"], energy: 2, description: "Sehr ruhiges, tiefgründiges Stück", lyrics: `REFRAIN:\nStille Nacht, laute Welt\nIch find' mich irgendwo dazwischen\nStille Nacht, laute Welt\nZwischen Schreien und dem Schweigen` },
  { id: 27, title: "Feuerwerk", key: "D-Dur", tempo: 135, duration: "3:55", mood: ["feierlich", "ausgelassen", "energiegeladen"], situation: ["party", "festival", "hochzeit", "konzert"], energy: 9, description: "Perfekter Finale-Song", lyrics: `REFRAIN:\nFeuerwerk – BOOM!\nAlles leuchtet auf\nFeuerwerk – BOOM!\nHält das Leben drauf\nFeuerwerk – für euch alle!` },
  { id: 28, title: "Wanderer", key: "H-Moll", tempo: 98, duration: "4:42", mood: ["nachdenklich", "entspannt", "melancholisch"], situation: ["akustik", "bar", "outdoor"], energy: 4, description: "Melancholisch-schöner Song", lyrics: `REFRAIN:\nWanderer, Wanderer\nZwischen Hier und Dort\nWanderer, Wanderer\nImmer weiter fort` },
  { id: 29, title: "Vollmond", key: "E-Dur", tempo: 112, duration: "4:08", mood: ["romantisch", "feierlich", "nachdenklich"], situation: ["outdoor", "hochzeit", "bar", "konzert"], energy: 6, description: "Mystischer Song", lyrics: `REFRAIN:\nVollmond, Vollmond\nZeig mir deinen Zauber\nVollmond, Vollmond\nMach die Nacht noch schöner` },
  { id: 30, title: "Letzter Tanz", key: "G-Moll", tempo: 90, duration: "5:10", mood: ["romantisch", "melancholisch", "feierlich"], situation: ["zugabe", "hochzeit", "konzert", "bar"], energy: 4, description: "Klassischer Zugabe-Song", lyrics: `REFRAIN:\nLetzter Tanz, letzter Tanz\nHält die Zeit für uns an\nLetzter Tanz, letzter Tanz\nDer schönste den's je gab\nLetzter Tanz` }
];

const MOOD_KEYWORDS = {
  energiegeladen: ["energie", "power", "stark", "wild", "feuer", "laut", "hard", "rock", "pump"],
  ausgelassen:    ["party", "feiern", "spaß", "lustig", "tanzen", "ausgelassen"],
  feierlich:      ["feier", "besonder", "würdig", "groß", "wichtig", "jubiläum"],
  romantisch:     ["liebe", "romantisch", "herz", "partner", "hochzeit", "verliebt"],
  melancholisch:  ["traurig", "nachdenklich", "tief", "bewegt", "emotional"],
  entspannt:      ["chill", "locker", "ruhig", "entspannt", "sanft", "leise"],
  nachdenklich:   ["nachdenken", "tief", "bedeutung", "philosophisch"],
  kraftvoll:      ["stark", "mächtig", "power", "kraftvoll", "massiv"]
};

const SITUATION_KEYWORDS = {
  konzert:  ["konzert", "gig", "auftritt", "bühne", "venue", "club"],
  festival: ["festival", "open air", "draußen", "sommer", "zelt"],
  outdoor:  ["outdoor", "draußen", "natur", "wald", "wiese", "berg"],
  party:    ["party", "feier", "geburtstag", "silvester", "feiern"],
  hochzeit: ["hochzeit", "heirat", "trauung", "brautpaar", "ehe"],
  bar:      ["bar", "kneipe", "pub", "lokal", "intim"],
  akustik:  ["akustik", "unplugged", "leise", "solo", "ruhig"],
  zugabe:   ["zugabe", "encore", "abschluss", "letzte"]
};

window.SONGS = SONGS;
window.MOOD_KEYWORDS = MOOD_KEYWORDS;
window.SITUATION_KEYWORDS = SITUATION_KEYWORDS;